services:
    dmzx.newtopic.listener:
        class: dmzx\newtopic\event\listener
        arguments:
            - '@template'
            - '@dbal.conn'
            - '@auth'
            - '@user'
            - '%core.php_ext%'
            - '%core.root_path%'
        tags:
            - { name: event.listener }            